name=BMP390_LTSM
version=1.0.1
author=Gavin Lyons <glyons66@hotmail.com>
maintainer=Gavin Lyons <glyons66@hotmail.com>
sentence=Arduino library for BMP390 sensors by Liontron systems
paragraph=BMP390 temperature and barometric pressure sensor, supports I2C or SPI, FIFO and interupt.
category=Sensors
url=https://github.com/gavinlyonsrepo/BMP390_LTSM
architectures=*

